### PR TITLE
Xcode8 update - property declared.

### PR DESCRIPTION
**Pull request by Harinder**
Xcode 8 (beta 5) related changes

### CODE REVIEW

**Comment by thomas-dang** [comment]
Looks good

**Comment by ashokds** [comment]
Looks good.

**Comment by ashokds** [comment]
We discussed it, and keeping this un-merged until Jenkins has xcode8 build integration ready.

**Comment by thomas-dang** [comment]
Closing this pull request as the necessary changes have already been merged up as part of https://github.com/DocuSignDev/ECSlidingViewController/pull/2

**Pull request closed without merging**
